### PR TITLE
Add target to travis

### PR DESCRIPTION
**Pull request by javierbertoli**

### CODE REVIEW

**Comment by javierbertoli** [comment]
@whiteinge, mind you check and enable travis for this repo? For some reason, I used my credentials but it's not working (I enabled it in the `Integrations & services` tab. I don't know if I'm missing something (I don't think so, but well... it's not working :smile: ) or is something related to the Travis migration to webhooks?

**Comment by whiteinge** [comment]
I'm kinda confused about how this is supposed to work too  :-P.  I'll talk to @gtmanfred this week about getting Travis enabled for the whole org.

The settings match other other formula repos and it looks like it's active in the Travis UI. Is it working now?

**Comment by javierbertoli** [comment]
@whiteinge, tbh, I don't know why/how, but suddenly it started working. I first thought that you enabled it but forgot to mention it here. But now, I understand from your comment that you did nothing either :smile: 

I  see no webhook was added and my credentials were removed from the 'Integration services' tab, so I guess 'something' was done from the Travis-CI side?

**Comment by whiteinge** [comment]
I did log in and toggled the on/off switches just in case so that must've unstuck whatever the problem was. 🤷‍♂️

**Pull request closed without merging**
